# Permalinks
permalink:           pretty

# Setup
title:               Ben Oren
tagline:             Pynchon was right
url:                 http://ben-oren.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ben Oren
  url:               bensdata@wordpress.com
  email:             oren.ben.k@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ben-oren

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
